### ISSUE TITLE
vercel `ISR` is not working

### ISSUE THREAD

**Issue by Vibes-INS** [magne4000/vite-plugin-vercel#10]
I want to be an ISR. I fork the demo of this project to a new warehouse for vercel deployment. But it not working.

demo github: https://github.com/Vibes-INS/vite-plugin-vercel-demo

### Vercel Config: 
<img width="932" alt="Screen Shot 2022-12-22 at 21 00 32" src="https://user-images.githubusercontent.com/33676809/209139740-d0012da1-8813-41c2-91cc-1d619dfe71e6.png">

### Result: 
<img width="1453" alt="Screen Shot 2022-12-22 at 21 01 45" src="https://user-images.githubusercontent.com/33676809/209139966-6e60acac-1290-4735-a5de-c2138e05cb43.png">

**Comment by magne4000** [comment]
I need to update a few things to supports last `vite-plugin-ssr` versions. Once it's done, it should also fix this issue. I'll keep this issue updated
