### ISSUE TITLE
ISR/Edge cache

### ISSUE THREAD

**Issue by nitedani** [magne4000/vite-plugin-vercel#100]
There is edge caching on vercel. Do we need ISR then? Is there a difference between edge cache and ISR? I think the only difference is that ISR is eager and edge cache is lazy? If edge caching is good enough, the complexity of ISR could be removed, and instead we can set the cache headers depending on the page, and use only one global ssr handler.

Example: https://astro-template.vercel.app/ssr-with-swr-caching
https://vercel.com/docs/edge-network/caching#using-vercel-functions

**Comment by magne4000** [comment]
There are also other differences between edge caching and ISR https://vercel.com/docs/incremental-static-regeneration#differences-between-isr-and-cache-control-headers

There is an overlap in functionality between the two, but they do not serve the same purpose of you know what you want. I do not plan to remove support for ISR.

**Comment by nitedani** [comment]
I see, I didn't know this :) Thank you!
