### ISSUE TITLE
Edge runtime is not compatible with ISR

### ISSUE THREAD

**Issue by nitedani** [magne4000/vite-plugin-vercel#102]
https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration
```
Good to know: The [edge runtime](https://nextjs.org/docs/pages/api-reference/edge) is currently not compatible with ISR, although you can leverage stale-while-revalidate by setting the cache-control header manually.
```

I have a few different ideas to solve this:
1. When runtime is edge, and isr is enabled for a specific page, set the pages runtime to node. (could be breaking user code)
2. When runtime is edge, and isr is enabled for a specific page, set the header 'Cache-Control', 's-maxage=15' in vercel config for the route. (maybe the the most simple for now)
3. Allow setting the runtime in +config.js for a specific page, and document isr only works with the node runtime. Also allow setting cache-control headers in +config.js https://github.com/vikejs/vike/issues/1803

**Comment by nitedani** [comment]
I see there is a TODO already: 😄 
https://github.com/magne4000/vite-plugin-vercel/blob/5a75f9477b571731563818beb49f1a67e02b25a1/packages/vike-integration/%2Bconfig.ts#L9-L15

Maybe headers could be implemented in vike code.

**Comment by magne4000** [comment]
My opinion is that if one has edge + ISR activated for an endpoint, it should be considered a configuration issue (and users should be warned accordingly).

**Comment by nitedani** [comment]
I agree, it's a configuration issue and we should throw an error. But I think we should also:
- support caching on the edge runtime(with cache-control headers set through +config.js)
- let the user choose the runtime through +config.js

**Comment by magne4000** [comment]
> For the second one, I think we can make two ssr bundles, one for edge and one for node

This should be fairly straightforward to implement, and I'll probably try this solution first.

> support caching on the edge(and node)

I need to see what I can do about that. I probably will not be able to try this soon, so any help is welcome on that matter :)

**Comment by magne4000** [comment]
Vike now supports `headers` and `edge` config :rocket:
