### ISSUE TITLE
Strange error trying to run `vite build` on Windows

### ISSUE THREAD

**Issue by typedrat** [magne4000/vite-plugin-vercel#11]
When I try to run `vite build`, I get the following error:

```
Failed to create output directory: mkdir C:\Users\awilliams\Development\synthetic-beauty-vite\.vercel\output\functions\C:: The filename, directory name, or volume label syntax is incorrect.
```

I have no idea where it's getting that path from, but it seems pretty obviously wrong.

**Comment by magne4000** [comment]
@typedrat should be fixed with latest version, could you give it a try?
