### ISSUE TITLE
not sure how this plugin works

### ISSUE THREAD

**Issue by dohomi** [magne4000/vite-plugin-vercel#114]
Hi

I thought I give your plugin a spin but somewhat I dont understand how it works. I added vite-plugin-vercel to my vite config and have my api endpoints inside of either a /api or /_api folder. When I run Vite there is no endpoint with the name /api/myFunctionName available. I checked your simple example and not sure what I would miss. I used `vercel dev` before but as I use Vite I thought I can eliminate my build step via tsup

Cheers

**Comment by magne4000** [comment]
My guess would be that it's somehow related to a specific Vite config, but without a reproduction repo, I'm not sure I can be of any help.

**Comment by magne4000** [comment]
Closing this issue until further details are provided.
