### ISSUE TITLE
Calling `getPagesAndRoutes()` too early

### ISSUE THREAD

**Issue by brillout** [magne4000/vite-plugin-vercel#122]
See https://github.com/vikejs/vike/issues/1956.

@magne4000 It seems like `@vite-plugin-vercel/vike` is calling `getPagesAndRoutes()` too early? @Areg472 Can you publish a reproduction?

**Comment by magne4000** [comment]
Indeed I would need a reproduction repo.

**Comment by Areg472** [comment]
https://github.com/Areg472/reproductionforvite

Here you go! This repo produces the same error :D

**Comment by brillout** [comment]
@magne4000 Let me know if you believe it's an issue on Vike's side.

**Comment by magne4000** [comment]
@Areg472 which version of node are you using?

**Comment by magne4000** [comment]
I'm unable to even reproduce the issue on Stackblitz: https://stackblitz.com/~/github.com/Areg472/reproductionforvite

**Comment by Areg472** [comment]
I am using node js 20.11.1

**Comment by Areg472** [comment]
Ok I found the issue. In my previous commits I had tracking codes for analytics in index.html file. I removed both of these 30 minutes later after repo publish and it seemed to be fixed.
