### ISSUE TITLE
How to make generate static page for a route

### ISSUE THREAD

**Issue by tabdon** [magne4000/vite-plugin-vercel#125]
Apologies if this was in the docs somewhere and I missed it.

I just want to have a static page generated for the root route '/'. Here's my vite.config:

```ts
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import vercel from 'vite-plugin-vercel';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(), 
    vercel()
  ],
})
```

When I run build I don't see any static files generated.

**Comment by magne4000** [comment]
You would need a framework like [Vike](https://vike.dev/pre-rendering) to prerender your pages, as Vite doesn't support this on its own, and it's [supported by `vite-plugin-vercel`](https://github.com/magne4000/vite-plugin-vercel?tab=readme-ov-file#usage-with-vike)
