### ISSUE TITLE
Route params in edge functions

### ISSUE THREAD

**Issue by Brendonovich** [magne4000/vite-plugin-vercel#13]
Are route parameters (segments inside `[]`) supported with edge functions?
I have a handler in `/edge/[target]/[arch]/[currentVersion].ts` and an `additionalEndpoints` config like so:
```ts
{
  source: `/edge/[dynamic]/[route].ts`,
  destination: `/api/[dynamic]/[route]`,
  edge: true
}
```
While I would expect this to work, Vercel is only deploying the function for the literal path `/api/[dynamic]/[route]` and not making it dynamic.

**Comment by magne4000** [comment]
Dynamic routes with this format are not supported, Vercel internally transforms those to regex. See https://vercel.com/docs/build-output-api/v3/configuration#routes

Internally I use [@vercel/routing-utils](https://www.npmjs.com/package/@vercel/routing-utils), so you can check how it works for your use case.

**Comment by Brendonovich** [comment]
Ah ok. I'm not quite sure how to use `getTransformedRoutes` and stuff, but would it be possible to use it and other stuff in Vercel's packages to make the plugin able to do the same regex transform? `vercel build` is able to do the segment-to-search-param transform, would be cool if this plugin could do the same.

**Comment by magne4000** [comment]
You can use `/path/:id` notation instead, which is supported by routing-utils by default. See [tests](https://github.com/vercel/vercel/blob/6115f0d74a90b1931ce500be2c3a05645c8529f6/packages/routing-utils/test/superstatic.spec.ts#L184) to check all supported syntaxes.

In your case, it would become:
```ts
{
  source: `/edge/:dynamic/:route`,
  destination: `/api/:dynamic/:route`,
  edge: true
}
```
