### ISSUE TITLE
https://test-vite-vercel-plugin.vercel.app/edge has crashed

### ISSUE THREAD

**Issue by douglasduteil** [magne4000/vite-plugin-vercel#14]
Hi @magne4000 
Does edge functions still works ?
https://test-vite-vercel-plugin.vercel.app/edge
![image](https://github.com/magne4000/vite-plugin-vercel/assets/730511/6de9925e-e1d0-40e7-a0bf-6f6b50e2a017)

**Comment by magne4000** [comment]
For some reason the Edge Config Database that this endpoint uses was disconnected from the project. It's now reconnected and works again
