### ISSUE TITLE
How to use Edge middleware?

### ISSUE THREAD

**Issue by Strydom** [magne4000/vite-plugin-vercel#31]
Hello,
Thanks for this repo!

I can't seem to figure out how to get [Edge middleware](https://vercel.com/docs/functions/edge-middleware) working.
I've tried adding a `middleware.ts` file along side my pages dir
```
src/pages/...
src/middleware.ts
```
which is not working.

I'm guessing I need to do something with `esbuild` or `additionalEndpoints` config to make sure it gets put into the right place in the `output`?

Or do i need to use https://github.com/egoist/vite-vercel. If yes, does this plugin play well with yours?

**Comment by Strydom** [comment]
I think i figured it out...

`vite.config.ts`
```
    config: {
      routes: [
        {
          src: '/(.*)',
          middlewarePath: "middleware",
          continue: true
        }
      ]
    },
    additionalEndpoints: [
      {
        source: 'src/middleware.ts',
        destination: `middleware`,
        edge: true,
        addRoute: false
      }
    ]
```

Middleware is now executing at least, but I'm getting errors
```
Error: Unable to find environment variable: `xxx`
```

**Comment by Strydom** [comment]
Oh looks like it might have been some cache or delay. Pushed a new version and it is working 👍🏻

**Comment by magne4000** [comment]
Have you tried adding the `middleware.ts` file at the root of your project? It seems to work as intended even with `vite-plugin-vercel` (without editing any config), which I admit I'm quite surprised.
