### ISSUE TITLE
Wrong Node.js runtime being used

### ISSUE THREAD

**Issue by Strydom** [magne4000/vite-plugin-vercel#32]
👋🏻 Hello

After deploying to Vercel, I've noticed the Node.js runtime being used for the `ssr_` function is on v16, although in my project settings I have v18 selected.

<img width="1173" alt="Screenshot 2023-10-21 at 14 51 31" src="https://github.com/magne4000/vite-plugin-vercel/assets/2946828/0ef249c3-8349-4be7-ad2b-a44929cb1519">

I've also tried to set the `package.json` engine to be `>=18`.

**Comment by magne4000** [comment]
Indeed currently node version is hard coded, I will update the behaviour so that it doesn't override configured version

**Comment by magne4000** [comment]
Published as `v2.0.0`

**Comment by Strydom** [comment]
Thanks, updated and working 👍🏻
