### ISSUE TITLE
CSR project does not copy dist to static directory

### ISSUE THREAD

**Issue by StringKe** [magne4000/vite-plugin-vercel#36]
Using edge provides api capability and I don't want the project to be modified to SSR.

my config
```ts
import { defineConfig } from 'vite';
import { compression } from 'vite-plugin-compression2';
import solid from 'vite-plugin-solid';
import topLevelAwait from 'vite-plugin-top-level-await';
import vercel from 'vite-plugin-vercel';
import wasm from 'vite-plugin-wasm';

import type { UserConfig } from 'vite';
import type { ViteVercelConfig } from 'vite-plugin-vercel';

export default defineConfig({
    plugins: [
        wasm(),
        topLevelAwait(),
        solid({
            dev: true,
            hot: true,
        }),
        compression(),
        vercel({
            smart: false,
        }),
    ],
    vercel: {},
    server: {
        port: 3000,
    },
    build: {
        rollupOptions: {
            output: {
                chunkFileNames: 'js/[name]-[hash:8].js',
                entryFileNames: 'js/[name]-[hash:8].js',
                assetFileNames: '[ext]/[name]-[hash:8].[ext]',
                manualChunks: (id) => {
                    if (id.includes('node_modules')) {
                        return 'vendor';
                    } else if (id.includes('src')) {
                        return 'app';
                    } else {
                        return 'common';
                    }
                },
            },
        },
    },
} as UserConfig & { vercel: ViteVercelConfig });

```

**Comment by magne4000** [comment]
@StringKe I'm not sure to understand correctly, could you be more explicit? Perhaps with an example of what you are trying to achieve?

**Comment by StringKe** [comment]
@magne4000  In my testing the `dist` directory is not deployed when `.vercel/output/function` exists.

![CleanShot 2023-12-26 at 20 08 21@2x](https://github.com/magne4000/vite-plugin-vercel/assets/31089228/5903e92d-4684-47e9-b9e0-59e8ee1d0ec2)

**Comment by magne4000** [comment]
@StringKe why did you expect your `dist` folder to be deployed? Is it declared somewhere in project definition?
FYI It's default behaviour of Vercel to only deploy `.vercel/output` when it exists, and the sole purpose of this repo is to create this folder. So if you only need what's inside your `dist` folder, you don't need this plugin at all.

**Comment by StringKe** [comment]
Since I'm a static site with some edge APIs, I expect to deploy the dist catalog.

**Comment by magne4000** [comment]
As this is not yet supported by this plugin, and I'm not convinced that it will be in the near future, I prefer to redirect you to the [official Vercel documentation](https://vercel.com/docs/functions/edge-functions/quickstart#create-an-edge-api-route), using the vercel cli instead of this plugin.
