### ISSUE TITLE
QUESTION: How do I manage environment variables in serverless functions?

### ISSUE THREAD

**Issue by Gawdfrey** [magne4000/vite-plugin-vercel#42]
Hey, sorry to open an issue for a question only..

I am looking at using this plugin to run a simple SPA that is able to proxy its requests through a backend to be able to obfuscate the requests. I am therefore in need of being able to set and read server-only environment variables in the functions.

Is that something that this plugin handles, or is that handled on the vercel platform. If the latter, am I only able to access `process.env` in the function, without touching anything in vite?

**Comment by magne4000** [comment]
Env vars are only handled on Vercel's side. You can of course access `process.env` in serverless functions.

> without touching anything in vite

What do you mean by that?
Vite supports SSR, and this plugin does so through [Vike](https://vike.dev) integration only for now. Any SSR related stuff handled by [Vike can make use of env vars](https://vike.dev/env).

But if you don't need that much complexity, you can just stick with using `process.env` in your servless functions, and it should just work.

**Comment by Gawdfrey** [comment]
Yeah, thats what I meant.
I was able to verify it on my own and thats why I closed the issue, just had some internal obstacles to jump over.

Thanks for the answer!
