### ISSUE TITLE
Update build target to `es2022`

### ISSUE THREAD

**Issue by kevbook** [magne4000/vite-plugin-vercel#75]
Would it be possible to update `standardBuildOptions.target` to  `es2022` instead of `es2020`

https://github.com/magne4000/vite-plugin-vercel/blob/4bb9352440780ede6a1ef47045c12a544e73b0f2/packages/vercel/src/build.ts#L97

**Comment by magne4000** [comment]
Good point, done is `v6.0.1`. It's a patch release as it should have no impact, as minimum node version supported by Vercel is `v18`.
