### ISSUE TITLE
use `globalThis.__dirname` effect `@vitejs/plugin-react-swc`

### ISSUE THREAD

**Issue by enpitsuLin** [magne4000/vite-plugin-vercel#9]
use `globalThis.__dirname` will cause `@vitejs/plugin-react-swc` to recognize the wrong module path in vite server mode

![Snipaste_2022-12-07_16-37-46](https://user-images.githubusercontent.com/29378026/206129399-5e374045-040d-452b-a360-671b980d8d66.png)

maybe there has some way not so Magic ?

I just remove `globalThis.__dirname = path.dirname(__filename)` in source code as my workaround, it work fine in my `"type":"module"` project

**Comment by enpitsuLin** [comment]
> In your case `__dirname` is already defined perhaps?

Actually, no. 

Only this library assigns a value to `globalThis.__dirname`

For unknown reasons `@vitejs/plugin-react-swc` checks the declaration of `__dirname` and uses it, which cause incorrect resolve in hmr

https://github.com/vitejs/vite-plugin-react-swc/blob/bd8703795e794075f53c052f3ff5211f14ce14e4/src/index.ts#L15,L18

**Comment by enpitsuLin** [comment]
@magne4000 latest version doesn’t cause this problem anymore, but hmr still not work properly which maybe cause by other package

**Comment by magne4000** [comment]
I'll take a quick look to check if any this plugin can cause hmr issues, but it's indeed more likely that's caused by some other package.
